services:
  app:
    image: ${APP_IMAGE:-uptime-guardian:version1.0.0}
    container_name: ug-app
    environment:
      - PORT=${APP_PORT:-3000}
      - RUNTIME=docker
    ports:
      - "${HOST_APP_PORT:-3000}:${APP_PORT:-3000}"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: ug-prom
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    depends_on:
      - app
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: ug-grafana
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-data:
